In [14]:
import numpy as np
import pandas as pd

In [12]:
np.arange(0,15)

mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat1)
mat2 = 2* mat1
print(mat2)
print('')
print(mat1 * mat2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[  2   8  18]
 [ 32  50  72]
 [ 98 128 162]]


In [10]:
vec = np.random.randn(10)
print(vec)
print(vec[5])
print(vec[2:4])
print(vec[np.arange(0,6,2)])

[ 0.14992037  0.35456557 -0.60092576  1.27889309  0.2676892   0.28060153
  0.62119065  0.33145562  1.35851851 -0.37884745]
0.28060152653348314
[-0.60092576  1.27889309]
[ 0.14992037 -0.60092576  0.2676892 ]


In [21]:
list = [1,2,3,4]
array = np.array(list)
print(pd.Series(list))
print(pd.Series(array))

df1 = pd.DataFrame(array, ['First', 'Second', 'Third', 'Fourth'])
print(df1)
print(df1.loc['Second'])

0    1
1    2
2    3
3    4
dtype: int64
0    1
1    2
2    3
3    4
dtype: int64
        0
First   1
Second  2
Third   3
Fourth  4
0    2
Name: Second, dtype: int64


In [28]:
dict1 = {
    "customers" : ["Amit", "Bob", "Chandan", "Denver"],
    "city" : ["Pune", "Mumbai", "Bangalore", "Chennai"],
    "contact" : ["9890123456", "8790987890", "7890098890", "7656789890"]
}

dict2 = {
    "customers" : ["Amit", "Bob", "Chandan", "Denver"],
    "company" : ["IBM", "TCS", "Infosys", "Wipro"],
    "salary" : ["12 LPA", "13 LPA", "11 LPA", "14 LPA"]
}


df2 = pd.DataFrame(dict1)
df3 = pd.DataFrame(dict2)
print(df2)
print(df2["city"])
print("")
print(df2.iloc[2])


  customers       city     contact
0      Amit       Pune  9890123456
1       Bob     Mumbai  8790987890
2   Chandan  Bangalore  7890098890
3    Denver    Chennai  7656789890
0         Pune
1       Mumbai
2    Bangalore
3      Chennai
Name: city, dtype: object

customers       Chandan
city          Bangalore
contact      7890098890
Name: 2, dtype: object


In [35]:
dict1 = {
    "customers" : ["Amit", "Bob", "Chandan", "Denver"],
    "city" : ["Pune", "Mumbai", "Bangalore", "Chennai"],
    "contact" : ["9890123456", "8790987890", "7890098890", "7656789890"]
}

dict2 = {
    "customers" : ["Amit", "Bob", "Chandan", "Denver"],
    "company" : ["IBM", "TCS", "Infosys", "Wipro"],
    "salary" : ["12 LPA", "13 LPA", "11 LPA", "14 LPA"]
}


df2 = pd.DataFrame(dict1)
df3 = pd.DataFrame(dict2)


print('Merge and Join Demo')

pd.merge(df2,df3, how="outer", on="customers")

Merge and Join Demo


customers       city     contact  company  salary
0      Amit       Pune  9890123456      IBM  12 LPA
1       Bob     Mumbai  8790987890      TCS  13 LPA
2   Chandan  Bangalore  7890098890  Infosys  11 LPA
3    Denver    Chennai  7656789890    Wipro  14 LPA

In [38]:
df3.sort_values(by="salary", inplace=True)
df3

customers  company  salary
2   Chandan  Infosys  11 LPA
0      Amit      IBM  12 LPA
1       Bob      TCS  13 LPA
3    Denver    Wipro  14 LPA

In [39]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])

flowers['daisy']

5

In [41]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[2,3]

39

In [42]:
data = {'prodID': ['101', '102', '103', '104', '104'],

                    'prodname': ['X', 'Y', 'Z', 'X', 'W'],

                     'profit': ['2738', '2727', '3497', '7347', '3743']}

dataframe = pd.DataFrame(data)

dataframe

grouped_data = dataframe.groupby('prodID')

grouped_data.max()

prodname profit
prodID                
101           X   2738
102           Y   2727
103           Z   3497
104           X   7347

In [48]:
s1 = pd.Series(['a', 'b'])

s2 = pd.Series(['c', 'd'])

pd.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: object

In [49]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [50]:
demo_array = np.arange(10,21)

subset_demo_array = demo_array[0:7]

subset_demo_array[:]= 101

subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])